export type CourtType = 'padel' | 'tennis';
export type City = 'brighton' | 'london';

export interface CourtLocation {
  id: string;
  name: string;
  type: CourtType;
  available: boolean;
  description: string;
  hasFloodLights?: boolean;
  price?: string;
  city: City;
  lat: number;
  lng: number;
  bookingUrl?: string;
}

const LTA = (slug: string, venueId: string) =>
  `https://www.lta.org.uk/play/book-a-tennis-court/courts/${slug}_${venueId}/`;

export const COURT_LOCATIONS: CourtLocation[] = [
  // Brighton
  {
    id: 'triangle-padel',
    name: 'Triangle Padel',
    type: 'padel',
    available: true,
    description: 'The Triangle Leisure Centre - Padel Courts',
    hasFloodLights: true,
    price: 'Membership',
    city: 'brighton',
    lat: 50.8397,
    lng: -0.1504,
  },
  {
    id: 'triangle-tennis',
    name: 'Triangle Tennis',
    type: 'tennis',
    available: true,
    description: 'The Triangle Leisure Centre - Tennis Courts',
    hasFloodLights: true,
    price: 'Membership',
    city: 'brighton',
    lat: 50.8397,
    lng: -0.1504,
  },
  {
    id: 'patcham-tennis',
    name: 'Patcham Tennis',
    type: 'tennis',
    available: true,
    description: 'Patcham Tennis Courts',
    hasFloodLights: false,
    price: '£9.30',
    city: 'brighton',
    lat: 50.8648,
    lng: -0.1512,
  },
  {
    id: 'hove-padel',
    name: 'Hove Padel',
    type: 'padel',
    available: true,
    description: 'Seafront Padel Courts',
    hasFloodLights: true,
    price: '£28.00',
    city: 'brighton',
    lat: 50.8212,
    lng: -0.1632,
  },
  {
    id: 'hove-tennis',
    name: 'Hove Tennis',
    type: 'tennis',
    available: true,
    description: 'Seafront Tennis Courts',
    hasFloodLights: true,
    price: '£8.90',
    city: 'brighton',
    lat: 50.8212,
    lng: -0.1632,
  },

  // London — LTA park tennis
  {
    id: 'archbishop-tennis',
    name: 'Archbishops Park',
    type: 'tennis',
    available: true,
    description: 'Archbishops Park Tennis Courts, Waterloo',
    hasFloodLights: false,
    price: '£7.70',
    city: 'london',
    lat: 51.4877,
    lng: -0.1254,
    bookingUrl: LTA('archbishops-park', '307b4855-9c90-4b69-b855-415ff80a7417'),
  },
  {
    id: 'geraldine-mary-tennis',
    name: 'Geraldine Mary Harmsworth',
    type: 'tennis',
    available: true,
    description: 'Geraldine Mary Harmsworth Park, Southwark',
    hasFloodLights: false,
    city: 'london',
    lat: 51.4945,
    lng: -0.1138,
    bookingUrl: LTA('geraldine-mary-harmsworth', '8d4edcff-b880-4e21-a027-ca82cc343fa5'),
  },
  {
    id: 'kennington-park-tennis',
    name: 'Kennington Park',
    type: 'tennis',
    available: true,
    description: 'Kennington Park — 5 floodlit courts',
    hasFloodLights: true,
    city: 'london',
    lat: 51.4824,
    lng: -0.1112,
    bookingUrl: LTA('kennington-park', '38f9b2bb-b840-45a9-9c6e-dc685f04ed25'),
  },
  {
    id: 'burgess-park-tennis',
    name: 'Burgess Park',
    type: 'tennis',
    available: true,
    description: 'Burgess Park Tennis Courts, Camberwell',
    hasFloodLights: false,
    city: 'london',
    lat: 51.4834,
    lng: -0.0779,
    bookingUrl: LTA('burgess-park', '12e87a80-3f5f-4985-9e81-eb064ba8f71b'),
  },
  {
    id: 'battersea-park-tennis',
    name: 'Battersea Park',
    type: 'tennis',
    available: true,
    description: 'Battersea Park — 16 outdoor courts',
    hasFloodLights: true,
    price: 'from £8',
    city: 'london',
    lat: 51.4769,
    lng: -0.1557,
    bookingUrl: LTA('battersea-park-tennis-courts', 'b2eed0a9-2cf4-4d9d-95b8-46248117c9ba'),
  },
  {
    id: 'clapham-common-tennis',
    name: 'Clapham Common',
    type: 'tennis',
    available: true,
    description: 'Clapham Common — 8 courts (5 floodlit)',
    hasFloodLights: true,
    city: 'london',
    lat: 51.4577,
    lng: -0.1478,
    bookingUrl: LTA('clapham-common', '2fb20762-62d1-4fc7-961c-f4404d4d1ae8'),
  },
  {
    id: 'vauxhall-park-tennis',
    name: 'Vauxhall Park',
    type: 'tennis',
    available: true,
    description: 'Vauxhall Park — 2 outdoor courts',
    hasFloodLights: false,
    city: 'london',
    lat: 51.4859,
    lng: -0.1239,
    bookingUrl: LTA('vauxhall-park', 'ed2c2180-e21f-494a-bf03-199755c45b64'),
  },
  {
    id: 'finsbury-park-tennis',
    name: 'Finsbury Park',
    type: 'tennis',
    available: true,
    description: 'Finsbury Park — 8 courts (6 floodlit)',
    hasFloodLights: true,
    city: 'london',
    lat: 51.571,
    lng: -0.1028,
    bookingUrl: LTA('finsbury-park', '422ffc17-2283-483d-8ec3-65f7fda31a05'),
  },
  {
    id: 'clissold-park-tennis',
    name: 'Clissold Park',
    type: 'tennis',
    available: true,
    description: 'Clissold Park, Stoke Newington — 8 courts (6 floodlit)',
    hasFloodLights: true,
    city: 'london',
    lat: 51.561,
    lng: -0.0849,
    bookingUrl: LTA('clissold-park', '24e84e6c-f529-4cd1-8793-cb0cc106e6e7'),
  },
  {
    id: 'victoria-park-tennis',
    name: 'Victoria Park',
    type: 'tennis',
    available: true,
    description: 'Victoria Park, Tower Hamlets',
    hasFloodLights: false,
    city: 'london',
    lat: 51.5355,
    lng: -0.0395,
    bookingUrl: LTA('tennis-courts-at-victoria-park', '6b29fc40-ca47-1067-b31d-714051078669'),
  },
  {
    id: 'london-fields-park-tennis',
    name: 'London Fields',
    type: 'tennis',
    available: true,
    description: 'London Fields Park, Hackney',
    hasFloodLights: false,
    city: 'london',
    lat: 51.5412,
    lng: -0.0573,
    bookingUrl: LTA('london-fields-park', 'c67a5893-b53e-4b77-8013-95fcfbe1526a'),
  },
  {
    id: 'southwark-park-tennis',
    name: 'Southwark Park',
    type: 'tennis',
    available: true,
    description: 'Southwark Park — 4 outdoor courts',
    hasFloodLights: false,
    city: 'london',
    lat: 51.4962,
    lng: -0.0568,
    bookingUrl: LTA('southwark-park', '4123ed12-8dd6-4f48-a706-6ab2fbde16ba'),
  },
  {
    id: 'tanner-st-park-tennis',
    name: 'Tanner Street Park',
    type: 'tennis',
    available: true,
    description: 'Tanner Street Park, Bermondsey — 4 courts',
    hasFloodLights: false,
    city: 'london',
    lat: 51.5018,
    lng: -0.0776,
    bookingUrl: LTA('tanner-st-park', '678288d9-d179-40aa-8727-9db920d15fdc'),
  },
  {
    id: 'myatts-fields-park-tennis',
    name: 'Myatts Fields Park',
    type: 'tennis',
    available: true,
    description: 'Myatts Fields Park, Camberwell',
    hasFloodLights: false,
    city: 'london',
    lat: 51.4742,
    lng: -0.1032,
    bookingUrl: LTA('myatts-fields-park', 'c7968b48-2c0c-4e2f-a2ae-850976a46f5e'),
  },
  {
    id: 'brockwell-park-tennis',
    name: 'Brockwell Park',
    type: 'tennis',
    available: true,
    description: 'Brockwell Park, Herne Hill — 6 courts',
    hasFloodLights: false,
    city: 'london',
    lat: 51.4514,
    lng: -0.1064,
    bookingUrl: LTA('brockwell-park', '03a2d315-2b9a-411d-8891-1bfde4cb4cf3'),
  },
  {
    id: 'stationers-park-tennis',
    name: 'Stationers Park',
    type: 'tennis',
    available: true,
    description: 'Stationers Park, Hornsey — 2 courts',
    hasFloodLights: false,
    city: 'london',
    lat: 51.5726,
    lng: -0.1278,
    bookingUrl: LTA('stationers-park', 'fdd0dd8d-f332-46a5-bb22-cb403ce136bf'),
  },
  {
    id: 'hackney-downs-park-tennis',
    name: 'Hackney Downs Park',
    type: 'tennis',
    available: true,
    description: 'Hackney Downs Park — 4 outdoor courts',
    hasFloodLights: false,
    city: 'london',
    lat: 51.5541,
    lng: -0.0602,
    bookingUrl: LTA('hackney-downs-park', '3df475ea-0986-403a-9f64-e520e234c73a'),
  },

  // London — Matchi padel
  {
    id: 'vauxhall-padel-yard',
    name: 'G4P Padel Yard (Vauxhall)',
    type: 'padel',
    available: true,
    description: 'Game4Padel — 3 outdoor courts, Vauxhall Square',
    hasFloodLights: true,
    price: '£70/hr',
    city: 'london',
    lat: 51.4848,
    lng: -0.1226,
    bookingUrl: 'https://www.matchi.se/facilities/g4pvauxhallpadelyard',
  },
  {
    id: 'tower-hill-padel',
    name: 'Tower Hill Terrace Padel',
    type: 'padel',
    available: true,
    description: 'London Sports Festival — outdoor court by Tower of London',
    hasFloodLights: true,
    price: '£50–55/hr',
    city: 'london',
    lat: 51.5083,
    lng: -0.076,
    bookingUrl: 'https://www.matchi.se/facilities/towerhillterrace',
  },
  {
    id: 'hays-galleria-padel',
    name: "Hay's Galleria Padel",
    type: 'padel',
    available: true,
    description: 'London Sports Festival — indoor court, London Bridge',
    hasFloodLights: false,
    price: '£60/hr',
    city: 'london',
    lat: 51.5054,
    lng: -0.0862,
    bookingUrl: 'https://www.matchi.se/facilities/londonbridgecity',
  },

  // London — book elsewhere (no live API in app)
  {
    id: 'hyde-park-tennis',
    name: 'Hyde Park Tennis',
    type: 'tennis',
    available: false,
    description: 'The Courts at Hyde Park — book via Royal Parks',
    hasFloodLights: true,
    price: 'from £9/hr',
    city: 'london',
    lat: 51.5078,
    lng: -0.1629,
    bookingUrl: 'https://sportsandleisure.royalparks.org.uk/hyde-park/sports-activities/adult-tennis',
  },
];

export const SEARCHABLE_COURTS = COURT_LOCATIONS.filter((c) => c.available);

export function getCourtById(id: string): CourtLocation | undefined {
  return COURT_LOCATIONS.find((c) => c.id === id);
}

export function courtsByCity(city: City): CourtLocation[] {
  return SEARCHABLE_COURTS.filter((c) => c.city === city);
}
